# Generated by Django 2.1.15 on 2020-06-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_admin', '0002_auto_20200619_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sousadmins',
            name='prénom',
            field=models.CharField(max_length=50, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='sousadmins',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Username'),
        ),
    ]
