# Generated by Django 2.1.15 on 2020-06-19 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface_admin', '0003_auto_20200619_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sousadmins',
            old_name='prénom',
            new_name='prenom',
        ),
        migrations.RemoveField(
            model_name='sousadmins',
            name='password',
        ),
        migrations.AlterField(
            model_name='sousadmins',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
