# Generated by Django 2.2.8 on 2020-04-26 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200426_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code_apogee', models.CharField(default=0, max_length=8)),
                ('nom', models.CharField(max_length=15)),
                ('prenom', models.CharField(max_length=15)),
                ('CIN', models.CharField(max_length=10)),
                ('Filiere', models.CharField(default=0, max_length=80)),
                ('cne', models.CharField(max_length=10)),
                ('complete', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sous_adm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('cne', models.CharField(max_length=10)),
                ('theme', models.CharField(choices=[('Dance', 'dance'), ('Music', 'music'), ('Theatre', 'theatre'), ('Dessin', 'dessin')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='theme_activ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=20)),
                ('img', models.ImageField(default='default.png', upload_to='')),
                ('description', models.TextField(default='defaultText')),
            ],
        ),
        migrations.CreateModel(
            name='evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(default='default.png', upload_to='')),
                ('lieu', models.CharField(max_length=50)),
                ('description', models.TextField(default='defaultText')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.club')),
            ],
        ),
        migrations.CreateModel(
            name='activite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sous_adm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Sous_adm')),
            ],
        ),
    ]
