# Generated by Django 2.2.8 on 2020-04-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_activite_annonce_club_etudiant_evenement_sous_adm_theme_activ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
