# Generated by Django 2.2.8 on 2020-06-14 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_con'),
    ]

    operations = [
        migrations.CreateModel(
            name='etudiant1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code_apogee', models.CharField(default=0, max_length=8)),
                ('nom', models.CharField(max_length=15)),
                ('prenom', models.CharField(max_length=15)),
                ('CIN', models.CharField(max_length=10)),
                ('Filiere', models.CharField(default=0, max_length=80)),
                ('cne', models.CharField(max_length=10)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
