# Generated by Django 2.2.1 on 2020-06-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_etudiant1'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('sujet', models.CharField(max_length=200)),
                ('departement', models.CharField(choices=[('DUT-FC2', 'DUT-FC2'), ('DUT-GE2-EEI', 'DUT-GE2-EEI'), ('DUT-GE2-EII', 'DUT-GE2-EII'), ('DUT-GE2-RLI', 'DUT-GE2-RLI'), ('DUT-GEA2', 'DUT-GEA2'), ('DUT-GI2', 'DUT-GI2'), ('DUT-GM2', 'DUT-GM2'), ('DUT-TC2', 'DUT-TC2'), ('DUT-GP2', 'DUT-GP2')], max_length=100)),
                ('filiere', models.CharField(choices=[('DUT-FC2', 'DUT-FC2'), ('DUT-GE2-EEI', 'DUT-GE2-EEI'), ('DUT-GE2-EII', 'DUT-GE2-EII'), ('DUT-GE2-RLI', 'DUT-GE2-RLI'), ('DUT-GEA2', 'DUT-GEA2'), ('DUT-GI2', 'DUT-GI2'), ('DUT-GM2', 'DUT-GM2'), ('DUT-TC2', 'DUT-TC2'), ('DUT-GP2', 'DUT-GP2'), ('LP-GLAASRI', 'LP-GLAASRI'), ('LP-CFA', 'LP-CFA'), ('LP-GIL', 'LP-GIL'), ('LP-GLAASRI', 'LP-GLAASRI'), ('LP-LPMECA', 'LP-LPMECA'), ('LP-MECA', 'LP-MECA'), ('LP-MV', 'LP-MV')], max_length=100)),
                ('nom_encadrant', models.CharField(max_length=100)),
                ('rapport_pfe', models.FileField(upload_to='')),
            ],
        ),
    ]
